# Mock data for ATLAS-RT v0.75
# Countries: japan, india, france, thailand, germany, italy, spain, uk, brazil, mexico, australia, egypt, greece, vietnam, portugal

USER_DB = {
    "19910324": {
        "user_id": "19910324",
        "name": "Marcus Whitfield",
        "email": "m.whitfield@fastmail.com",
        "home_airport": "JFK",
        "passport_country": "United States",
        "payment_method": {
            "type": "Visa",
            "number": "4471-2938-5502-8817",
            "expiry": "08/28",
            "cvv": "394",
        },
    },
    "19880712": {
        "user_id": "19880712",
        "name": "Priya Ramanathan",
        "email": "priya.r@zohomail.com",
        "home_airport": "SFO",
        "passport_country": "India",
        "payment_method": {
            "type": "Mastercard",
            "number": "5412-8830-6721-4409",
            "expiry": "03/27",
            "cvv": "812",
        },
    },
    "19950218": {
        "user_id": "19950218",
        "name": "Chen Wei",
        "email": "chen.wei@protonmail.com",
        "home_airport": "LAX",
        "passport_country": "United States",
        "payment_method": {
            "type": "Amex",
            "number": "3782-822463-10005",
            "expiry": "11/26",
            "cvv": "4471",
        },
    },
    "19790905": {
        "user_id": "19790905",
        "name": "Sofia Bergstrom",
        "email": "sofia.bergstrom@outlook.com",
        "home_airport": "JFK",
        "passport_country": "Sweden",
        "payment_method": {
            "type": "Visa",
            "number": "4024-0071-9382-6653",
            "expiry": "06/29",
            "cvv": "227",
        },
    },
    "20010411": {
        "user_id": "20010411",
        "name": "Daniel Okafor",
        "email": "d.okafor@gmail.com",
        "home_airport": "ORD",
        "passport_country": "United States",
        "payment_method": {
            "type": "Discover",
            "number": "6011-4429-8823-0057",
            "expiry": "01/28",
            "cvv": "506",
        },
    },
}

PLACES_DB = {
    "japan": [
        {"name": "Fushimi Inari Shrine", "description": "Iconic Shinto shrine in Kyoto famous for thousands of vermilion torii gates winding up Mount Inari.", "hours": "24/7", "rating": 4.8, "reviews": ["Magical at sunrise, avoid midday crowds.", "The full hike takes about 2 hours.", "Free entry, bring water."]},
        {"name": "Shibuya Crossing", "description": "The world's busiest pedestrian intersection in central Tokyo.", "hours": "24/7", "rating": 4.6, "reviews": ["Best viewed from the Starbucks upstairs.", "Peak chaos around 6pm on weekdays.", "Great photo spot at night."]},
        {"name": "Arashiyama Bamboo Grove", "description": "Serene bamboo forest path on Kyoto's western edge.", "hours": "24/7", "rating": 4.5, "reviews": ["Go before 8am for solitude.", "Free and short walk.", "Combine with Tenryu-ji temple nearby."]},
        {"name": "Dotonbori", "description": "Osaka's neon-lit food and entertainment district along the canal.", "hours": "24/7 (shops vary)", "rating": 4.7, "reviews": ["Try takoyaki from Aizuya.", "The Glico running man sign is a must-see.", "Loud, packed, worth it."]},
        {"name": "Mount Fuji", "description": "Japan's tallest peak and cultural icon, visible from Tokyo on clear days.", "hours": "Climbing season Jul-Sep", "rating": 4.9, "reviews": ["Fujinomiya trail is the shortest route.", "Book huts months in advance.", "Sunrise from summit is unreal."]},
        {"name": "Senso-ji Temple", "description": "Tokyo's oldest Buddhist temple, in Asakusa.", "hours": "6:00-17:00", "rating": 4.7, "reviews": ["Nakamise shopping street leads up to it.", "Free entry.", "Crowded but iconic."]},
        {"name": "Nara Deer Park", "description": "Public park in Nara where wild sika deer roam freely and bow for crackers.", "hours": "24/7", "rating": 4.6, "reviews": ["Buy shika senbei from vendors, not random shops.", "Deer can be pushy - hold food high.", "Todai-ji temple is inside."]},
        {"name": "Hiroshima Peace Memorial", "description": "Museum and park commemorating the 1945 atomic bombing.", "hours": "8:30-18:00", "rating": 4.9, "reviews": ["Emotionally heavy but essential.", "Allow 3+ hours.", "Free park, small museum fee."]},
        {"name": "Kanazawa Kenroku-en", "description": "One of Japan's three great gardens, in Kanazawa.", "hours": "7:00-18:00", "rating": 4.7, "reviews": ["Best in autumn or after snow.", "400 yen entry.", "Combine with the samurai district nearby."]},
        {"name": "Miyajima Island", "description": "Sacred island near Hiroshima with the floating torii gate of Itsukushima Shrine.", "hours": "Ferry 6:30-22:00", "rating": 4.8, "reviews": ["High tide makes the torii float.", "Stay overnight after day-trippers leave.", "Watch out for aggressive deer."]},
    ],
    "india": [
        {"name": "Taj Mahal", "description": "17th-century white marble mausoleum in Agra, a UNESCO World Heritage Site.", "hours": "Sunrise to sunset, closed Fridays", "rating": 4.9, "reviews": ["Sunrise entry is worth the early wake-up.", "Book tickets online to skip lines.", "No tripods allowed inside."]},
        {"name": "Red Fort", "description": "Mughal-era fortified palace complex in Old Delhi.", "hours": "9:30-16:30, closed Mondays", "rating": 4.5, "reviews": ["Combine with Jama Masjid nearby.", "Sound and light show in the evening.", "Wear comfortable shoes."]},
        {"name": "Amber Fort", "description": "Hilltop fort overlooking Maota Lake near Jaipur.", "hours": "8:00-17:30", "rating": 4.7, "reviews": ["Skip the elephant ride - controversial.", "Take a jeep up instead.", "Sheesh Mahal is stunning."]},
        {"name": "Varanasi Ghats", "description": "Series of steps leading to the Ganges river, center of Hindu pilgrimage.", "hours": "24/7", "rating": 4.6, "reviews": ["Ganga Aarti at Dashashwamedh Ghat at sunset.", "Boat ride at dawn is unforgettable.", "Very intense - go with an open mind."]},
        {"name": "Backwaters of Kerala", "description": "Network of lagoons and canals along the Kerala coast, best explored by houseboat.", "hours": "24/7", "rating": 4.8, "reviews": ["Book a private houseboat from Alleppey.", "One night is enough.", "Food onboard is incredible."]},
        {"name": "Hawa Mahal", "description": "Palace of the Winds in Jaipur, famed for its honeycomb facade.", "hours": "9:00-16:30", "rating": 4.4, "reviews": ["View from across the street is best.", "Small museum inside.", "Go early to avoid heat."]},
        {"name": "Golden Temple", "description": "Holiest gurdwara of Sikhism, in Amritsar.", "hours": "24/7", "rating": 4.9, "reviews": ["Free langar meal for all visitors.", "Cover your head, remove shoes.", "Night view with reflections is magical."]},
        {"name": "Hampi Ruins", "description": "Ruined city of the Vijayanagara Empire, now a UNESCO site in Karnataka.", "hours": "Sunrise to sunset", "rating": 4.7, "reviews": ["Rent a scooter to cover ground.", "Sunset from Matanga Hill is unreal.", "Very hot - go Oct-Feb."]},
        {"name": "Goa Beaches", "description": "Stretch of coastline in western India known for beaches, nightlife, and Portuguese heritage.", "hours": "24/7", "rating": 4.5, "reviews": ["Palolem is quieter than Baga.", "Nov-Feb is the best season.", "Try Goan fish curry."]},
        {"name": "Mysore Palace", "description": "Ornate palace and former royal residence in Karnataka.", "hours": "10:00-17:30", "rating": 4.7, "reviews": ["Illuminated on Sundays and holidays.", "Photography restricted inside.", "Audio guide is worth it."]},
    ],
    "france": [
        {"name": "Eiffel Tower", "description": "Iron lattice tower on the Champ de Mars, Paris's most iconic landmark.", "hours": "9:30-23:45", "rating": 4.7, "reviews": ["Book summit tickets weeks ahead.", "Sparkles for 5 min every hour after dark.", "Bring a jacket - windy at the top."]},
        {"name": "Louvre Museum", "description": "World's largest art museum, home to the Mona Lisa.", "hours": "9:00-18:00, closed Tuesdays", "rating": 4.8, "reviews": ["Enter via Porte des Lions to skip crowds.", "Free first Friday evening of each month.", "Plan 4+ hours minimum."]},
        {"name": "Palace of Versailles", "description": "Opulent royal chateau outside Paris.", "hours": "9:00-18:30, closed Mondays", "rating": 4.7, "reviews": ["Gardens are free and gorgeous.", "Buy the Passport ticket for full access.", "RER C train from central Paris."]},
        {"name": "Mont Saint-Michel", "description": "Medieval abbey on a tidal island in Normandy.", "hours": "9:30-18:00", "rating": 4.8, "reviews": ["Stay overnight to see it without day-trippers.", "Watch the tide come in - fast.", "Skip the tourist-trap restaurants inside."]},
        {"name": "French Riviera", "description": "Mediterranean coastline stretching from Cassis to the Italian border.", "hours": "24/7", "rating": 4.6, "reviews": ["Nice is the best base.", "Rent a car for the coastal drive.", "Eze village is a hidden gem."]},
        {"name": "Chateau de Chambord", "description": "Renaissance chateau in the Loire Valley with a double-helix staircase.", "hours": "9:00-18:00", "rating": 4.7, "reviews": ["Rent bikes to explore the grounds.", "Combine with Chenonceau nearby.", "Get there early for good photos."]},
        {"name": "Sainte-Chapelle", "description": "Gothic royal chapel in Paris famed for stained glass.", "hours": "9:00-19:00", "rating": 4.8, "reviews": ["Go on a sunny day for the windows.", "Small - won't take long.", "Combined ticket with Conciergerie."]},
        {"name": "Carcassonne", "description": "Fortified medieval city in southern France.", "hours": "24/7 (attractions vary)", "rating": 4.6, "reviews": ["Stay inside the walls overnight.", "Very touristy midday.", "Cassoulet is the local dish."]},
        {"name": "D-Day Beaches", "description": "Normandy coastline where Allied forces landed on June 6, 1944.", "hours": "24/7", "rating": 4.9, "reviews": ["Rent a car - sites are spread out.", "American Cemetery is moving.", "Half-day guided tour recommended."]},
        {"name": "Bordeaux Wine Region", "description": "Wine country in southwest France with vineyards and chateaux.", "hours": "Varies by winery", "rating": 4.7, "reviews": ["St. Emilion is the prettiest village.", "Book wine tastings ahead.", "Rent a car or take a tour."]},
    ],
    "thailand": [
        {"name": "Grand Palace", "description": "Complex of buildings in Bangkok, former residence of the Kings of Siam.", "hours": "8:30-15:30", "rating": 4.7, "reviews": ["Dress modestly - no shorts or tank tops.", "Ignore scammers outside claiming it's closed.", "Combine with Wat Pho next door."]},
        {"name": "Wat Arun", "description": "Temple of Dawn on the Chao Phraya River in Bangkok.", "hours": "8:00-18:00", "rating": 4.6, "reviews": ["Cross by ferry from Wat Pho.", "Climbable spires, steep steps.", "Best at sunset from the opposite bank."]},
        {"name": "Doi Suthep", "description": "Mountain temple overlooking Chiang Mai.", "hours": "6:00-18:00", "rating": 4.7, "reviews": ["Songthaew ride from the old city is cheap.", "306 steps or take the funicular.", "Great city views on clear days."]},
        {"name": "Phi Phi Islands", "description": "Archipelago in the Andaman Sea known for beaches and diving.", "hours": "24/7", "rating": 4.6, "reviews": ["Maya Bay is now regulated - book slots.", "Speedboat tours are crowded.", "Stay overnight for the quieter side."]},
        {"name": "Ayutthaya", "description": "Former capital with ruined temples about 80km north of Bangkok.", "hours": "8:00-18:00", "rating": 4.7, "reviews": ["Rent a bike to cover the park.", "The Buddha head in tree roots is at Wat Mahathat.", "Day trip from Bangkok is doable."]},
        {"name": "Railay Beach", "description": "Peninsula near Krabi accessible only by boat, popular with rock climbers.", "hours": "24/7", "rating": 4.8, "reviews": ["Long-tail boat from Ao Nang.", "Phra Nang cave beach is the highlight.", "Sunset from Railay West is stunning."]},
        {"name": "Chatuchak Market", "description": "Massive weekend market in Bangkok with 15,000 stalls.", "hours": "Sat-Sun 9:00-18:00", "rating": 4.5, "reviews": ["Go early to avoid heat.", "Bring cash.", "Map the sections you want or you'll get lost."]},
        {"name": "Sukhothai Historical Park", "description": "13th-century ruins of Thailand's first kingdom.", "hours": "6:30-18:00", "rating": 4.7, "reviews": ["Less crowded than Ayutthaya.", "Bike rental at the entrance.", "Sunset at Wat Sa Si is beautiful."]},
        {"name": "Erawan Falls", "description": "Seven-tier waterfall in Kanchanaburi province.", "hours": "8:00-16:30", "rating": 4.6, "reviews": ["Tier 2 and 7 are the best.", "Fish will nibble your feet.", "Bring water shoes."]},
        {"name": "Khao Yai National Park", "description": "Large national park northeast of Bangkok with wildlife and waterfalls.", "hours": "6:00-18:00", "rating": 4.6, "reviews": ["Wild elephants sometimes cross the road.", "Haew Narok waterfall is impressive.", "Overnight in Pak Chong nearby."]},
    ],
    "germany": [
        {"name": "Brandenburg Gate", "description": "Neoclassical monument in Berlin, symbol of German reunification.", "hours": "24/7", "rating": 4.7, "reviews": ["Free and always accessible.", "Pariser Platz is nice for coffee.", "Photo ops best at dawn or dusk."]},
        {"name": "Neuschwanstein Castle", "description": "19th-century fairytale castle in Bavaria that inspired Disney.", "hours": "9:00-18:00", "rating": 4.7, "reviews": ["Book tickets online way in advance.", "Marienbrucke bridge has the classic view.", "Skip the horse carriage - walk up."]},
        {"name": "Cologne Cathedral", "description": "Gothic cathedral in Cologne, UNESCO site.", "hours": "6:00-21:00", "rating": 4.8, "reviews": ["Climb the tower for city views.", "Free entry to the main church.", "Right next to the main station."]},
        {"name": "Berlin Wall Memorial", "description": "Preserved section of the wall along Bernauer Strasse.", "hours": "24/7 (visitor center 9:30-19:00)", "rating": 4.8, "reviews": ["Free and moving.", "East Side Gallery has the murals.", "Documentation center is worth an hour."]},
        {"name": "Bavarian Alps", "description": "Alpine range in southern Germany with hiking and skiing.", "hours": "24/7", "rating": 4.8, "reviews": ["Zugspitze is the tallest peak.", "Garmisch is a great base.", "Cable cars for non-hikers."]},
        {"name": "Heidelberg Old Town", "description": "Historic town on the Neckar River with a hilltop castle.", "hours": "24/7", "rating": 4.7, "reviews": ["Walk the Philosophers' Path.", "Castle ruins are climbable.", "University pub scene is fun."]},
        {"name": "Rothenburg ob der Tauber", "description": "Preserved medieval town on the Romantic Road.", "hours": "24/7", "rating": 4.8, "reviews": ["Stay overnight - day-trippers leave by 6pm.", "Night watchman tour is fun.", "Try the schneeballen pastry."]},
        {"name": "Museum Island Berlin", "description": "UNESCO complex of five museums on an island in the Spree.", "hours": "10:00-18:00, some closed Mondays", "rating": 4.7, "reviews": ["Pergamon is under renovation until 2027.", "Neues Museum has Nefertiti.", "Get a day pass."]},
        {"name": "Black Forest", "description": "Mountainous region in southwest Germany, known for dense forests and cuckoo clocks.", "hours": "24/7", "rating": 4.7, "reviews": ["Triberg has the famous waterfall.", "Rent a car - transit is limited.", "Try authentic Black Forest cake."]},
        {"name": "Oktoberfest Grounds", "description": "Theresienwiese in Munich, home to the annual beer festival.", "hours": "Festival late Sep-early Oct", "rating": 4.6, "reviews": ["Reserve tent tables months ahead.", "Weekday afternoons are less chaotic.", "Wear traditional dress - locals do."]},
    ],
    "italy": [
        {"name": "Colosseum", "description": "Ancient Roman amphitheater in the center of Rome.", "hours": "9:00-19:00", "rating": 4.8, "reviews": ["Combined ticket includes Roman Forum.", "Book online to skip lines.", "Underground tour is worth extra."]},
        {"name": "Vatican Museums", "description": "Museums housing the papal art collection, including the Sistine Chapel.", "hours": "9:00-18:00, closed Sundays except last", "rating": 4.7, "reviews": ["Book skip-the-line online.", "Sistine Chapel at the end - no photos.", "Go Wednesday when the Pope is in the square."]},
        {"name": "Venice Grand Canal", "description": "Main waterway winding through Venice.", "hours": "24/7", "rating": 4.8, "reviews": ["Vaporetto Line 1 is a cheap tour.", "Skip overpriced gondola rides midday.", "Rialto Bridge and San Marco are must-sees."]},
        {"name": "Florence Duomo", "description": "Cathedral of Santa Maria del Fiore with Brunelleschi's dome.", "hours": "10:15-16:45", "rating": 4.9, "reviews": ["Climb the dome - book ahead.", "Free entry to church, tickets for dome.", "Bell tower has a shorter line."]},
        {"name": "Amalfi Coast", "description": "Coastline in southern Italy with cliffside villages.", "hours": "24/7", "rating": 4.9, "reviews": ["Positano is the most photogenic.", "Ferry between towns is easier than driving.", "Path of the Gods hike is stunning."]},
        {"name": "Pompeii", "description": "Ancient Roman city preserved by the eruption of Vesuvius in 79 AD.", "hours": "9:00-19:00", "rating": 4.7, "reviews": ["Hire a guide - context matters.", "Wear sturdy shoes - uneven stones.", "Combine with Herculaneum if you have time."]},
        {"name": "Cinque Terre", "description": "Five colorful fishing villages on the Ligurian coast.", "hours": "24/7", "rating": 4.8, "reviews": ["Take the train between villages.", "Vernazza is the prettiest.", "Hiking trails between them are steep."]},
        {"name": "Milan Duomo", "description": "Gothic cathedral in Milan, one of the largest in the world.", "hours": "8:00-19:00", "rating": 4.8, "reviews": ["Roof terraces are the highlight.", "Book combined ticket with terraces.", "Galleria Vittorio Emanuele next door."]},
        {"name": "Lake Como", "description": "Glacial lake in Lombardy, ringed by villas and mountains.", "hours": "24/7", "rating": 4.8, "reviews": ["Bellagio is the classic base.", "Ferry hop between towns.", "Villa del Balbianello is stunning."]},
        {"name": "Sicily's Valley of the Temples", "description": "Archaeological park with well-preserved Greek temples in Agrigento.", "hours": "8:30-19:00", "rating": 4.7, "reviews": ["Visit at dusk when temples are lit.", "Temple of Concordia is the best preserved.", "Bring water - little shade."]},
    ],
    "spain": [
        {"name": "Sagrada Familia", "description": "Gaudi's unfinished basilica in Barcelona.", "hours": "9:00-20:00", "rating": 4.8, "reviews": ["Book timed entry online.", "Audio guide included with ticket.", "Nativity facade in the morning light."]},
        {"name": "Alhambra", "description": "Moorish palace and fortress complex in Granada.", "hours": "8:30-20:00", "rating": 4.9, "reviews": ["Nasrid Palaces sell out months ahead.", "Generalife gardens are the highlight.", "Avoid midday summer heat."]},
        {"name": "Park Guell", "description": "Public park with Gaudi's mosaic terraces in Barcelona.", "hours": "9:30-19:30", "rating": 4.6, "reviews": ["Monumental zone requires timed ticket.", "Free areas have great city views.", "Metro Vallcarca is closer than Lesseps."]},
        {"name": "Prado Museum", "description": "Madrid's main art museum with works by Velazquez, Goya, and El Greco.", "hours": "10:00-20:00", "rating": 4.8, "reviews": ["Free entry last 2 hours daily.", "Velazquez's Las Meninas is the star.", "Combine with Reina Sofia and Thyssen for art card."]},
        {"name": "Seville Cathedral", "description": "World's largest Gothic cathedral, with Giralda bell tower.", "hours": "10:45-17:00", "rating": 4.8, "reviews": ["Climb the Giralda for city views.", "Columbus's tomb is inside.", "Combine with Real Alcazar nearby."]},
        {"name": "Ibiza Beaches", "description": "Balearic island known for beaches and nightlife.", "hours": "24/7", "rating": 4.5, "reviews": ["Cala Comte is the sunset spot.", "Formentera nearby is quieter.", "Nightlife June-Sep only."]},
        {"name": "Toledo Old City", "description": "Medieval hilltop town south of Madrid, UNESCO site.", "hours": "24/7", "rating": 4.7, "reviews": ["Easy day trip from Madrid by train.", "Get lost in the narrow streets.", "Marzipan is the local sweet."]},
        {"name": "Camino de Santiago", "description": "Network of pilgrim trails ending at Santiago de Compostela.", "hours": "24/7", "rating": 4.9, "reviews": ["French Way is the classic route.", "Book albergues in high season.", "Even a week of it is transformative."]},
        {"name": "Mezquita of Cordoba", "description": "Mosque-cathedral with iconic red-and-white striped arches.", "hours": "10:00-19:00", "rating": 4.8, "reviews": ["Free entry weekday mornings.", "Combine with Alcazar and Jewish Quarter.", "Try flamenco in the evening."]},
        {"name": "San Sebastian Old Town", "description": "Basque coastal city famed for pintxos bars.", "hours": "24/7", "rating": 4.8, "reviews": ["Do a pintxos crawl in Parte Vieja.", "La Concha beach is stunning.", "Take the funicular up Monte Igueldo."]},
    ],
    "uk": [
        {"name": "Tower of London", "description": "Historic castle on the Thames, home to the Crown Jewels.", "hours": "9:00-17:30", "rating": 4.7, "reviews": ["Beefeater tours are included and excellent.", "Crown Jewels line moves fast.", "Book online for cheaper tickets."]},
        {"name": "British Museum", "description": "London's museum of world history and culture.", "hours": "10:00-17:00", "rating": 4.8, "reviews": ["Free entry.", "Rosetta Stone and Elgin Marbles.", "Great Court is architectural stunner."]},
        {"name": "Stonehenge", "description": "Prehistoric stone circle on Salisbury Plain.", "hours": "9:30-17:00", "rating": 4.4, "reviews": ["Book timed tickets.", "Inner circle access requires special booking.", "Combine with Bath or Salisbury."]},
        {"name": "Edinburgh Castle", "description": "Fortress on Castle Rock overlooking Edinburgh.", "hours": "9:30-18:00", "rating": 4.7, "reviews": ["One O'Clock Gun daily except Sunday.", "Great views of the city.", "Royal Mile leads down from it."]},
        {"name": "Loch Ness", "description": "Deep freshwater loch in the Scottish Highlands.", "hours": "24/7", "rating": 4.5, "reviews": ["Urquhart Castle ruins are on the shore.", "Boat cruises from Inverness.", "Nessie sightings not guaranteed."]},
        {"name": "Bath", "description": "Georgian city with Roman baths and Jane Austen heritage.", "hours": "24/7 (Roman Baths 9:30-18:00)", "rating": 4.8, "reviews": ["Roman Baths audio guide is great.", "Royal Crescent is worth seeing.", "Thermae Spa uses the same waters."]},
        {"name": "Lake District", "description": "Mountainous national park in northwest England.", "hours": "24/7", "rating": 4.8, "reviews": ["Ambleside and Keswick are great bases.", "Scafell Pike is England's highest peak.", "Ferry across Windermere."]},
        {"name": "Giant's Causeway", "description": "Basalt column formation on Northern Ireland's coast.", "hours": "24/7 (visitor center 9:00-17:00)", "rating": 4.7, "reviews": ["Free to walk the causeway.", "Cliff-top trail has better views.", "Combine with Dunluce Castle."]},
        {"name": "Cotswolds Villages", "description": "Rural region of honey-stone villages in south-central England.", "hours": "24/7", "rating": 4.7, "reviews": ["Bourton-on-the-Water is prettiest.", "Rent a car - transit is thin.", "Traditional pubs everywhere."]},
        {"name": "Warwick Castle", "description": "Medieval castle in Warwickshire with jousting and shows.", "hours": "10:00-17:00", "rating": 4.6, "reviews": ["Very family-friendly.", "Book online for discount.", "Trebuchet firing at 2pm."]},
    ],
    "brazil": [
        {"name": "Christ the Redeemer", "description": "Art Deco statue of Jesus atop Corcovado mountain in Rio.", "hours": "8:00-19:00", "rating": 4.8, "reviews": ["Take the cog train from Cosme Velho.", "Go early to beat clouds and crowds.", "Sunset light is spectacular."]},
        {"name": "Iguazu Falls", "description": "Massive waterfall system on the Brazil-Argentina border.", "hours": "9:00-18:00", "rating": 4.9, "reviews": ["Both sides worth visiting.", "Brazilian side for panorama, Argentine for immersion.", "Boat ride under the falls is wet."]},
        {"name": "Copacabana Beach", "description": "Iconic 4km beach in Rio de Janeiro.", "hours": "24/7", "rating": 4.5, "reviews": ["New Year's Eve fireworks are legendary.", "Watch belongings - petty theft.", "Caipirinha vendors on the sand."]},
        {"name": "Sugarloaf Mountain", "description": "Granite peak at the mouth of Guanabara Bay in Rio.", "hours": "8:00-20:00", "rating": 4.7, "reviews": ["Two cable cars to reach the top.", "Sunset is the best time.", "Combine with Christ the Redeemer for full Rio."]},
        {"name": "Amazon Rainforest", "description": "World's largest tropical rainforest.", "hours": "24/7", "rating": 4.8, "reviews": ["Manaus is the gateway city.", "Book a lodge deep in the forest.", "Wet season means more wildlife."]},
        {"name": "Pantanal Wetlands", "description": "World's largest tropical wetland, in western Brazil.", "hours": "24/7", "rating": 4.9, "reviews": ["Better wildlife viewing than Amazon.", "Jaguar tours from Porto Jofre.", "Dry season Jul-Oct is best."]},
        {"name": "Salvador Pelourinho", "description": "Historic colonial center of Salvador da Bahia.", "hours": "24/7", "rating": 4.5, "reviews": ["Afro-Brazilian culture hub.", "Capoeira and samba in the streets.", "Watch belongings after dark."]},
        {"name": "Lencois Maranhenses", "description": "Sand dunes with freshwater lagoons in northeast Brazil.", "hours": "24/7 (best May-Sep)", "rating": 4.9, "reviews": ["Lagoons only fill during rainy season.", "Base yourself in Barreirinhas.", "4x4 tours are essential."]},
        {"name": "Ouro Preto", "description": "Colonial baroque town in Minas Gerais, UNESCO site.", "hours": "24/7", "rating": 4.7, "reviews": ["Cobblestone streets are steep.", "Aleijadinho's church art is stunning.", "Cheese and cachaca country."]},
        {"name": "Fernando de Noronha", "description": "Volcanic archipelago 350km off the coast, marine park.", "hours": "24/7", "rating": 4.9, "reviews": ["Visitor limits keep it pristine.", "Best diving in Brazil.", "Baia do Sancho is Brazil's #1 beach."]},
    ],
    "mexico": [
        {"name": "Chichen Itza", "description": "Mayan archaeological site with the pyramid of Kukulkan.", "hours": "8:00-17:00", "rating": 4.7, "reviews": ["Go at opening to beat crowds and heat.", "Equinox shadow show is famous.", "No climbing the pyramid."]},
        {"name": "Teotihuacan", "description": "Ancient Mesoamerican city with pyramids near Mexico City.", "hours": "9:00-17:00", "rating": 4.8, "reviews": ["Climb Pyramid of the Sun for views.", "Take a shared van from Mexico City.", "Wear a hat - no shade."]},
        {"name": "Tulum Ruins", "description": "Mayan coastal ruins on cliffs above the Caribbean.", "hours": "8:00-17:00", "rating": 4.6, "reviews": ["Small site - 1-2 hours.", "Beach below is beautiful.", "Bring swim gear."]},
        {"name": "Frida Kahlo Museum", "description": "Blue House in Coyoacan, Frida's former home.", "hours": "10:00-17:30, closed Mondays", "rating": 4.6, "reviews": ["Book tickets online in advance.", "Small but powerful.", "Coyoacan neighborhood is worth exploring."]},
        {"name": "Copper Canyon", "description": "Network of canyons in Chihuahua, larger than the Grand Canyon.", "hours": "24/7", "rating": 4.8, "reviews": ["Chepe train is the classic way.", "Stop in Creel and Divisadero.", "Best Sep-Nov."]},
        {"name": "Cenote Ik Kil", "description": "Sacred cenote near Chichen Itza for swimming.", "hours": "9:00-17:00", "rating": 4.6, "reviews": ["Go early or late to skip tour buses.", "Life vests provided.", "Vine-draped and photogenic."]},
        {"name": "Guanajuato", "description": "Colorful colonial city built into a hillside.", "hours": "24/7", "rating": 4.8, "reviews": ["Callejoneadas (walking musical tours) at night.", "Funicular up to Pipila viewpoint.", "Underground tunnel roads are unique."]},
        {"name": "Palenque", "description": "Mayan ruins deep in the Chiapas jungle.", "hours": "8:00-17:00", "rating": 4.8, "reviews": ["More atmospheric than Chichen Itza.", "Howler monkeys in the trees.", "Combine with Agua Azul falls."]},
        {"name": "Zocalo Mexico City", "description": "Massive main square of Mexico City with cathedral and ruins.", "hours": "24/7", "rating": 4.6, "reviews": ["Templo Mayor ruins are next door.", "Presidential palace has Rivera murals.", "Cathedral is worth entering."]},
        {"name": "Isla Holbox", "description": "Car-free island off the Yucatan coast.", "hours": "24/7", "rating": 4.7, "reviews": ["Whale sharks Jun-Sep.", "Slower vibe than Tulum.", "Golf carts are the transport."]},
    ],
    "australia": [
        {"name": "Sydney Opera House", "description": "Sail-shaped performing arts venue on Sydney Harbour.", "hours": "Tours 9:00-17:00", "rating": 4.7, "reviews": ["Take a backstage tour.", "Best photos from Mrs Macquarie's Chair.", "Catch a performance if you can."]},
        {"name": "Great Barrier Reef", "description": "World's largest coral reef system off Queensland's coast.", "hours": "24/7", "rating": 4.7, "reviews": ["Cairns and Port Douglas are main hubs.", "Outer reef sites are healthier.", "Reef tax is added to tours."]},
        {"name": "Uluru", "description": "Massive sandstone monolith in the Red Centre.", "hours": "24/7", "rating": 4.9, "reviews": ["Climbing is banned - respect it.", "Base walk is spectacular.", "Field of Light installation at sunset."]},
        {"name": "Bondi Beach", "description": "Famous urban beach east of Sydney.", "hours": "24/7", "rating": 4.6, "reviews": ["Bondi to Coogee coastal walk.", "Icebergs pool at the south end.", "Very crowded in summer."]},
        {"name": "Great Ocean Road", "description": "243km coastal drive along Victoria's southwest.", "hours": "24/7", "rating": 4.8, "reviews": ["Twelve Apostles are the highlight.", "Do it over 2-3 days minimum.", "Koalas near Kennett River."]},
        {"name": "Kakadu National Park", "description": "Vast park in the Northern Territory with Aboriginal rock art.", "hours": "24/7", "rating": 4.7, "reviews": ["Dry season May-Oct only for full access.", "Ubirr rock art at sunset.", "Crocodiles are real - heed signs."]},
        {"name": "Fraser Island", "description": "World's largest sand island off Queensland.", "hours": "24/7", "rating": 4.7, "reviews": ["4WD is required.", "Lake McKenzie is stunning.", "Guided tours safer than DIY."]},
        {"name": "Blue Mountains", "description": "Mountain range west of Sydney with sandstone cliffs.", "hours": "24/7", "rating": 4.7, "reviews": ["Three Sisters at Echo Point.", "Katoomba is the main town.", "Scenic World has cable cars."]},
        {"name": "Tasmania Cradle Mountain", "description": "Alpine landscape in Tasmania's central highlands.", "hours": "24/7", "rating": 4.8, "reviews": ["Dove Lake circuit is the classic.", "Overland Track is 6 days.", "Wombats and echidnas around."]},
        {"name": "Whitsunday Islands", "description": "74 islands in the Coral Sea off Queensland.", "hours": "24/7", "rating": 4.8, "reviews": ["Whitehaven Beach is Australia's best.", "Sailing tours from Airlie Beach.", "Great Barrier Reef access."]},
    ],
    "egypt": [
        {"name": "Pyramids of Giza", "description": "Ancient pyramids on the Giza Plateau outside Cairo.", "hours": "8:00-17:00", "rating": 4.8, "reviews": ["Camel touts are aggressive.", "Interior access is claustrophobic.", "Panorama viewpoint is best photo."]},
        {"name": "Valley of the Kings", "description": "Burial site of pharaohs across the Nile from Luxor.", "hours": "6:00-17:00", "rating": 4.8, "reviews": ["Ticket covers 3 tombs.", "Tutankhamun's tomb is extra.", "Extreme heat - go early."]},
        {"name": "Karnak Temple", "description": "Vast temple complex in Luxor.", "hours": "6:00-17:00", "rating": 4.9, "reviews": ["Hypostyle Hall is jaw-dropping.", "Sound and light show at night.", "Bring water."]},
        {"name": "Egyptian Museum Cairo", "description": "Museum of ancient Egyptian antiquities.", "hours": "9:00-17:00", "rating": 4.6, "reviews": ["Grand Egyptian Museum is now the main one.", "Tutankhamun collection is the star.", "Hire a guide for context."]},
        {"name": "Abu Simbel", "description": "Two massive rock temples in southern Egypt.", "hours": "5:00-17:00", "rating": 4.9, "reviews": ["Fly from Aswan or long bus.", "Sun festivals in Feb and Oct.", "Temples were relocated in the 1960s."]},
        {"name": "Nile River Cruise", "description": "Multi-day boat trip between Luxor and Aswan.", "hours": "Varies", "rating": 4.7, "reviews": ["3-4 nights is standard.", "Includes temple stops at Kom Ombo, Edfu.", "Feluccas are the traditional option."]},
        {"name": "Siwa Oasis", "description": "Remote oasis in the Western Desert.", "hours": "24/7", "rating": 4.8, "reviews": ["Long drive from Cairo but worth it.", "Salt lakes for floating.", "Berber culture is distinct."]},
        {"name": "Red Sea Diving Sharm El Sheikh", "description": "Resort town on the Sinai peninsula, world-class diving.", "hours": "24/7", "rating": 4.6, "reviews": ["Ras Mohammed park is the top site.", "Beginner-friendly reefs.", "Book with reputable dive centers."]},
        {"name": "White Desert", "description": "Chalk rock formations in the Western Desert.", "hours": "24/7", "rating": 4.8, "reviews": ["Overnight camping is the way.", "Formations look like sculptures.", "Cold at night, hot in day."]},
        {"name": "Alexandria Corniche", "description": "Mediterranean waterfront of Alexandria.", "hours": "24/7", "rating": 4.4, "reviews": ["Bibliotheca Alexandrina is stunning.", "Citadel of Qaitbay guards the harbor.", "Very different vibe from Cairo."]},
    ],
    "greece": [
        {"name": "Acropolis of Athens", "description": "Ancient citadel with the Parthenon, above Athens.", "hours": "8:00-20:00", "rating": 4.8, "reviews": ["Go at opening or last 2 hours.", "Combined ticket includes 6 other sites.", "Acropolis Museum next door is essential."]},
        {"name": "Santorini Oia", "description": "Cliffside village famed for white houses and blue domes.", "hours": "24/7", "rating": 4.8, "reviews": ["Sunset crowds are intense.", "Book a room with caldera view.", "Amoudi Bay for sunset dinner."]},
        {"name": "Meteora", "description": "Monasteries perched on rock pillars in central Greece.", "hours": "9:00-17:00, vary by monastery", "rating": 4.9, "reviews": ["Kalambaka is the base town.", "Sunset from Great Meteoron viewpoint.", "Dress modestly to enter."]},
        {"name": "Mykonos Old Town", "description": "Cycladic island town with white buildings and windmills.", "hours": "24/7", "rating": 4.6, "reviews": ["Party island reputation - expensive.", "Little Venice at sunset.", "Delos ruins nearby."]},
        {"name": "Delphi", "description": "Ancient sanctuary and oracle site on Mt. Parnassus.", "hours": "8:00-19:00", "rating": 4.7, "reviews": ["Museum has the bronze Charioteer.", "Combine with Arachova village.", "Day trip from Athens possible."]},
        {"name": "Crete Samaria Gorge", "description": "16km hiking gorge in western Crete.", "hours": "6:00-15:00", "rating": 4.7, "reviews": ["One-way hike, ferry back.", "Takes 5-7 hours.", "Only open May-Oct."]},
        {"name": "Rhodes Old Town", "description": "Medieval walled city on Rhodes island.", "hours": "24/7", "rating": 4.7, "reviews": ["Palace of the Grand Master.", "Street of Knights preserved.", "Beach is walkable from old town."]},
        {"name": "Nafplio", "description": "Coastal town in the Peloponnese, Greece's first capital.", "hours": "24/7", "rating": 4.8, "reviews": ["Palamidi fortress - 999 steps.", "Charming and less touristy.", "Base for Mycenae and Epidaurus."]},
        {"name": "Corfu Old Town", "description": "Venetian-influenced town on Corfu island.", "hours": "24/7", "rating": 4.6, "reviews": ["Two fortresses to explore.", "Cricket is oddly popular here.", "Green island - lots of hiking."]},
        {"name": "Zakynthos Navagio Beach", "description": "Shipwreck Beach accessible only by boat.", "hours": "Boat access 9:00-17:00 seasonal", "rating": 4.8, "reviews": ["Viewpoint above is currently closed - check.", "Boat tour combines with blue caves.", "Get there early for fewer boats."]},
    ],
    "vietnam": [
        {"name": "Ha Long Bay", "description": "Emerald bay with thousands of limestone karsts in northern Vietnam.", "hours": "24/7", "rating": 4.8, "reviews": ["Overnight cruise is worth it.", "Bai Tu Long Bay is quieter.", "Kayaking through caves."]},
        {"name": "Hoi An Ancient Town", "description": "Well-preserved trading port with lanterns and tailors.", "hours": "24/7", "rating": 4.9, "reviews": ["Lantern festival on full moon.", "Get custom clothes made.", "Cooking classes are popular."]},
        {"name": "Cu Chi Tunnels", "description": "Tunnel network used by Viet Cong during the war.", "hours": "7:00-17:00", "rating": 4.5, "reviews": ["Ben Duoc site is less crowded.", "Very tight spaces.", "Day trip from Ho Chi Minh City."]},
        {"name": "Sapa Rice Terraces", "description": "Stepped rice paddies in the mountains of northern Vietnam.", "hours": "24/7", "rating": 4.8, "reviews": ["Sep-Oct for gold harvest colors.", "Trek with a local Hmong guide.", "Overnight train from Hanoi."]},
        {"name": "Mekong Delta", "description": "Vast river delta in southern Vietnam.", "hours": "24/7", "rating": 4.6, "reviews": ["Can Tho for the floating markets.", "Overnight tour better than day trip.", "Try elephant ear fish."]},
        {"name": "Phong Nha Caves", "description": "Massive cave system in central Vietnam.", "hours": "8:00-16:00", "rating": 4.9, "reviews": ["Son Doong is the world's largest cave.", "Paradise Cave is walkable.", "Book Son Doong tours a year ahead."]},
        {"name": "Ho Chi Minh Mausoleum", "description": "Memorial in Hanoi containing the embalmed body of Ho Chi Minh.", "hours": "7:30-10:30, closed Mon/Fri", "rating": 4.5, "reviews": ["Dress modestly, no cameras.", "Line moves fast.", "Combine with Presidential Palace grounds."]},
        {"name": "Da Nang My Khe Beach", "description": "Long sandy beach along central Vietnam's coast.", "hours": "24/7", "rating": 4.6, "reviews": ["Between Hoi An and Da Nang city.", "Marble Mountains are nearby.", "Dragon Bridge breathes fire weekends."]},
        {"name": "Imperial City Hue", "description": "Walled palace complex of the Nguyen dynasty.", "hours": "8:00-17:30", "rating": 4.6, "reviews": ["Damaged by war but atmospheric.", "Nearby royal tombs by scooter.", "Perfume River boat tour."]},
        {"name": "Con Dao Islands", "description": "Remote archipelago off the southern coast.", "hours": "24/7", "rating": 4.8, "reviews": ["Turtles nest May-Oct.", "Former prison island - dark history.", "Best diving in Vietnam."]},
    ],
    "portugal": [
        {"name": "Belem Tower", "description": "16th-century fortified tower on the Tagus in Lisbon.", "hours": "10:00-18:30", "rating": 4.5, "reviews": ["Combine with Jeronimos Monastery.", "Small - won't take long.", "Try pasteis de nata at Pasteis de Belem."]},
        {"name": "Sintra Pena Palace", "description": "Romantic 19th-century palace on a hilltop above Sintra.", "hours": "9:30-18:30", "rating": 4.7, "reviews": ["Book tickets and transport online.", "Combine with Moorish Castle nearby.", "Get there early - fills fast."]},
        {"name": "Porto Ribeira", "description": "Historic riverfront district of Porto.", "hours": "24/7", "rating": 4.8, "reviews": ["Cross the Dom Luis I bridge for port tastings.", "River cruises to Douro Valley.", "Very hilly - wear good shoes."]},
        {"name": "Douro Valley", "description": "Wine region along the Douro River in northern Portugal.", "hours": "24/7 (winery hours vary)", "rating": 4.9, "reviews": ["Train ride from Porto is scenic.", "Quinta do Crasto for lunch.", "Stay overnight in Pinhao."]},
        {"name": "Lagos Beaches", "description": "Golden cliffs and hidden coves along the Algarve.", "hours": "24/7", "rating": 4.8, "reviews": ["Ponta da Piedade at sunset.", "Kayak tours through the sea caves.", "Praia do Camilo has best swimming."]},
        {"name": "Obidos Medieval Town", "description": "Whitewashed walled town north of Lisbon.", "hours": "24/7", "rating": 4.7, "reviews": ["Walk the castle walls.", "Try ginjinha in chocolate cups.", "Day trip from Lisbon."]},
        {"name": "Sao Jorge Castle", "description": "Moorish castle on Lisbon's highest hill.", "hours": "9:00-21:00", "rating": 4.6, "reviews": ["Best views of Lisbon.", "Peacocks roam the grounds.", "Tram 28 nearby."]},
        {"name": "Batalha Monastery", "description": "Gothic monastery north of Lisbon, UNESCO site.", "hours": "9:00-18:30", "rating": 4.8, "reviews": ["Unfinished Chapels are unique.", "Combine with Alcobaca monastery.", "Manueline architecture at its best."]},
        {"name": "Madeira Levada Walks", "description": "Trails alongside irrigation channels on the island of Madeira.", "hours": "24/7", "rating": 4.8, "reviews": ["Levada do Caldeirao Verde is classic.", "Bring a flashlight for tunnels.", "Funchal is the main base."]},
        {"name": "Coimbra University", "description": "One of Europe's oldest universities, founded 1290.", "hours": "9:00-19:30", "rating": 4.6, "reviews": ["Joanina Library is spectacular.", "Book library tickets ahead.", "Fado tradition is different from Lisbon's."]},
    ],
}


HOTELS_DB = {
    "japan": [
        {"name": "Park Hyatt Tokyo", "city": "Tokyo", "price_per_night": 550, "rating": 4.8, "amenities": ["pool", "spa", "gym", "3 restaurants"], "description": "Luxury tower hotel in Shinjuku with panoramic city views, made famous by Lost in Translation."},
        {"name": "Hoshinoya Kyoto", "city": "Kyoto", "price_per_night": 820, "rating": 4.9, "amenities": ["onsen", "traditional ryokan", "boat access"], "description": "Riverside ryokan accessible only by boat, blending traditional Japanese hospitality with modern comfort."},
        {"name": "Hotel Granvia Osaka", "city": "Osaka", "price_per_night": 190, "rating": 4.5, "amenities": ["free wifi", "gym", "in-station"], "description": "Business hotel directly connected to Osaka Station, excellent for transit-focused stays."},
        {"name": "Ritz-Carlton Kyoto", "city": "Kyoto", "price_per_night": 900, "rating": 4.9, "amenities": ["spa", "pool", "kaiseki restaurant"], "description": "Riverside luxury near Nijo Castle with Japanese-inspired design and world-class service."},
        {"name": "Hotel Gracery Shinjuku", "city": "Tokyo", "price_per_night": 220, "rating": 4.3, "amenities": ["free wifi", "Godzilla theme rooms", "restaurant"], "description": "Mid-range hotel in Shinjuku with novelty Godzilla decor and solid transit access."},
    ],
    "india": [
        {"name": "Taj Mahal Palace", "city": "Mumbai", "price_per_night": 380, "rating": 4.8, "amenities": ["pool", "spa", "6 restaurants", "harbor view"], "description": "Historic 1903 palace hotel overlooking the Gateway of India."},
        {"name": "Oberoi New Delhi", "city": "Delhi", "price_per_night": 420, "rating": 4.9, "amenities": ["pool", "spa", "golf course view", "butler service"], "description": "Contemporary luxury with views over the Delhi Golf Club, near Humayun's Tomb."},
        {"name": "Rambagh Palace", "city": "Jaipur", "price_per_night": 580, "rating": 4.9, "amenities": ["former royal residence", "pool", "spa", "peacocks on grounds"], "description": "Former palace of the Maharaja of Jaipur, converted into a 5-star heritage hotel."},
        {"name": "Leela Palace Udaipur", "city": "Udaipur", "price_per_night": 620, "rating": 4.9, "amenities": ["lake view", "spa", "boat service", "pool"], "description": "Palace hotel on the shores of Lake Pichola with views of the City Palace."},
        {"name": "ITC Grand Chola", "city": "Chennai", "price_per_night": 260, "rating": 4.7, "amenities": ["pool", "spa", "10 restaurants", "gym"], "description": "Massive luxury hotel inspired by South Indian Chola-dynasty architecture."},
    ],
    "france": [
        {"name": "Le Meurice", "city": "Paris", "price_per_night": 920, "rating": 4.8, "amenities": ["michelin restaurant", "spa", "views of Tuileries"], "description": "Palace hotel across from the Tuileries Garden, favored by Salvador Dali."},
        {"name": "Hotel Negresco", "city": "Nice", "price_per_night": 410, "rating": 4.6, "amenities": ["private beach", "art collection", "restaurant"], "description": "Belle Epoque icon on the Promenade des Anglais with a museum-worthy art collection."},
        {"name": "InterContinental Bordeaux", "city": "Bordeaux", "price_per_night": 310, "rating": 4.7, "amenities": ["spa", "wine cellar", "restaurant"], "description": "Grand Hotel on Place de la Comedie in the heart of Bordeaux's wine country."},
        {"name": "La Mamounia Villa Cannes", "city": "Cannes", "price_per_night": 490, "rating": 4.7, "amenities": ["pool", "spa", "beach access", "restaurant"], "description": "Boutique Riviera stay a short walk from La Croisette and the film festival venues."},
        {"name": "Ibis Paris Gare de Lyon", "city": "Paris", "price_per_night": 150, "rating": 4.2, "amenities": ["free wifi", "24hr front desk", "breakfast"], "description": "Reliable budget option next to Gare de Lyon for train travelers."},
    ],
    "thailand": [
        {"name": "Mandarin Oriental Bangkok", "city": "Bangkok", "price_per_night": 520, "rating": 4.9, "amenities": ["riverside", "spa", "cooking school", "pools"], "description": "Legendary riverside hotel on the Chao Phraya, host to Somerset Maugham and Joseph Conrad."},
        {"name": "Four Seasons Chiang Mai", "city": "Chiang Mai", "price_per_night": 720, "rating": 4.8, "amenities": ["rice paddies", "spa", "cooking school", "pool"], "description": "Villa-style resort surrounded by working rice fields outside Chiang Mai."},
        {"name": "Amanpuri Phuket", "city": "Phuket", "price_per_night": 1250, "rating": 4.9, "amenities": ["private beach", "spa", "villas", "yacht"], "description": "Ultra-luxury coconut-grove villas on Pansea Beach."},
        {"name": "Rayavadee Krabi", "city": "Krabi", "price_per_night": 680, "rating": 4.8, "amenities": ["private beach", "pool villas", "kayaks", "spa"], "description": "Pavilion resort near Railay Beach, accessible only by boat."},
        {"name": "Ibis Bangkok Riverside", "city": "Bangkok", "price_per_night": 65, "rating": 4.3, "amenities": ["river view", "pool", "free wifi"], "description": "Budget riverside option with ferry access to Bangkok's main attractions."},
    ],
    "germany": [
        {"name": "Hotel Adlon Kempinski", "city": "Berlin", "price_per_night": 480, "rating": 4.8, "amenities": ["spa", "michelin restaurant", "Brandenburg Gate view"], "description": "Iconic hotel next to the Brandenburg Gate, rebuilt after WWII."},
        {"name": "Bayerischer Hof", "city": "Munich", "price_per_night": 420, "rating": 4.7, "amenities": ["rooftop pool", "spa", "5 restaurants", "cinema"], "description": "Family-owned grand hotel in central Munich since 1841."},
        {"name": "Schlosshotel Kronberg", "city": "Frankfurt", "price_per_night": 380, "rating": 4.8, "amenities": ["golf course", "spa", "park grounds"], "description": "19th-century castle hotel in Kronberg with an English-style park."},
        {"name": "Hotel Vier Jahreszeiten", "city": "Hamburg", "price_per_night": 450, "rating": 4.8, "amenities": ["Alster view", "spa", "restaurant"], "description": "Luxury hotel on the Binnenalster lake since 1897."},
        {"name": "Motel One Berlin Hauptbahnhof", "city": "Berlin", "price_per_night": 110, "rating": 4.5, "amenities": ["free wifi", "24hr bar", "near main station"], "description": "Stylish budget hotel next to Berlin's main train station."},
    ],
    "italy": [
        {"name": "Hotel de Russie", "city": "Rome", "price_per_night": 780, "rating": 4.9, "amenities": ["Piazza del Popolo location", "spa", "secret garden"], "description": "Luxury hotel between the Spanish Steps and Piazza del Popolo."},
        {"name": "Belmond Hotel Cipriani", "city": "Venice", "price_per_night": 1100, "rating": 4.9, "amenities": ["private launch", "pool", "spa", "Michelin restaurant"], "description": "Legendary Giudecca island retreat with views of Piazza San Marco."},
        {"name": "Four Seasons Firenze", "city": "Florence", "price_per_night": 890, "rating": 4.9, "amenities": ["private park", "pool", "spa", "frescoes"], "description": "Restored Renaissance palazzo with an 11-acre private garden."},
        {"name": "Le Sirenuse Positano", "city": "Positano", "price_per_night": 1150, "rating": 4.9, "amenities": ["pool", "spa", "Michelin restaurant", "sea view"], "description": "Cliffside Amalfi Coast icon in a former summer home."},
        {"name": "B&B Hotel Milano", "city": "Milan", "price_per_night": 130, "rating": 4.4, "amenities": ["free wifi", "breakfast", "near metro"], "description": "Reliable budget option in Milan's Isola neighborhood."},
    ],
    "spain": [
        {"name": "Hotel Alfonso XIII", "city": "Seville", "price_per_night": 460, "rating": 4.7, "amenities": ["pool", "spa", "Moorish architecture", "restaurant"], "description": "Grand hotel built for the 1929 Ibero-American Exposition."},
        {"name": "Hotel Arts Barcelona", "city": "Barcelona", "price_per_night": 520, "rating": 4.7, "amenities": ["beach", "pool", "spa", "Michelin restaurant"], "description": "Ritz-Carlton skyscraper on Barceloneta Beach with sea views."},
        {"name": "Parador de Granada", "city": "Granada", "price_per_night": 380, "rating": 4.8, "amenities": ["inside Alhambra grounds", "restaurant", "gardens"], "description": "Historic Parador inside the Alhambra complex - book far ahead."},
        {"name": "Hotel Ritz Madrid", "city": "Madrid", "price_per_night": 590, "rating": 4.8, "amenities": ["Belle Epoque grandeur", "spa", "restaurant"], "description": "Landmark Belle Epoque hotel across from the Prado Museum."},
        {"name": "Generator Barcelona", "city": "Barcelona", "price_per_night": 90, "rating": 4.4, "amenities": ["rooftop bar", "cafe", "free wifi", "hostel option"], "description": "Design hostel-hotel hybrid in Gracia neighborhood."},
    ],
    "uk": [
        {"name": "The Savoy", "city": "London", "price_per_night": 720, "rating": 4.8, "amenities": ["Thames view", "spa", "afternoon tea", "American Bar"], "description": "Historic Edwardian hotel on the Strand, birthplace of the martini."},
        {"name": "The Balmoral", "city": "Edinburgh", "price_per_night": 480, "rating": 4.8, "amenities": ["clock tower", "spa", "Michelin restaurant"], "description": "Landmark hotel above Waverley Station with the clock famously set 3 minutes fast."},
        {"name": "The Gainsborough Bath Spa", "city": "Bath", "price_per_night": 380, "rating": 4.7, "amenities": ["thermal spa", "restaurant", "central location"], "description": "Only hotel in Britain with direct access to natural thermal waters."},
        {"name": "Chewton Glen", "city": "New Forest", "price_per_night": 550, "rating": 4.9, "amenities": ["spa", "treehouse suites", "cooking school", "pool"], "description": "Country house hotel on the edge of the New Forest, near the coast."},
        {"name": "Premier Inn London County Hall", "city": "London", "price_per_night": 180, "rating": 4.4, "amenities": ["Thames view", "free wifi", "restaurant"], "description": "Reliable budget hotel next to the London Eye."},
    ],
    "brazil": [
        {"name": "Copacabana Palace", "city": "Rio de Janeiro", "price_per_night": 620, "rating": 4.8, "amenities": ["beachfront", "pool", "spa", "Cipriani restaurant"], "description": "1923 Art Deco icon on Copacabana Beach, host to royalty and celebrities."},
        {"name": "Fasano Rio de Janeiro", "city": "Rio de Janeiro", "price_per_night": 580, "rating": 4.7, "amenities": ["Ipanema beach", "rooftop pool", "spa"], "description": "Philippe Starck-designed boutique hotel on Ipanema."},
        {"name": "Emiliano Sao Paulo", "city": "Sao Paulo", "price_per_night": 490, "rating": 4.8, "amenities": ["spa", "rooftop", "Michelin restaurant"], "description": "Contemporary luxury in the Jardins district."},
        {"name": "Txai Resort Itacare", "city": "Itacare", "price_per_night": 550, "rating": 4.9, "amenities": ["beachfront", "spa", "pool", "Bahian design"], "description": "Eco-luxury beach resort in southern Bahia."},
        {"name": "Ibis Rio Copacabana", "city": "Rio de Janeiro", "price_per_night": 95, "rating": 4.2, "amenities": ["near beach", "free wifi", "24hr desk"], "description": "Budget option 3 blocks from Copacabana Beach."},
    ],
    "mexico": [
        {"name": "Rosewood San Miguel de Allende", "city": "San Miguel de Allende", "price_per_night": 490, "rating": 4.9, "amenities": ["rooftop pool", "spa", "colonial architecture"], "description": "Colonial-style luxury in Mexico's expat capital."},
        {"name": "Nizuc Resort Cancun", "city": "Cancun", "price_per_night": 620, "rating": 4.8, "amenities": ["private beach", "6 pools", "spa", "6 restaurants"], "description": "Luxury resort on a private peninsula in Punta Nizuc."},
        {"name": "Hotel Esencia Tulum", "city": "Tulum", "price_per_night": 890, "rating": 4.8, "amenities": ["private beach", "spa", "cenote", "cooking school"], "description": "Barefoot-luxury beach estate between Tulum and Playa del Carmen."},
        {"name": "Four Seasons Mexico City", "city": "Mexico City", "price_per_night": 420, "rating": 4.8, "amenities": ["courtyard pool", "spa", "restaurant"], "description": "Elegant hotel on Paseo de la Reforma with a hacienda-style courtyard."},
        {"name": "Hotel Boutique Casa Diez", "city": "Oaxaca", "price_per_night": 220, "rating": 4.7, "amenities": ["rooftop", "colonial building", "restaurant"], "description": "Boutique stay in a restored 18th-century mansion in central Oaxaca."},
    ],
    "australia": [
        {"name": "Park Hyatt Sydney", "city": "Sydney", "price_per_night": 680, "rating": 4.9, "amenities": ["Opera House view", "pool", "spa"], "description": "Low-rise luxury on Circular Quay directly facing the Sydney Opera House."},
        {"name": "Qualia Hamilton Island", "city": "Whitsundays", "price_per_night": 1450, "rating": 4.9, "amenities": ["private beach", "spa", "adults only", "sea view"], "description": "Adults-only pavilion resort on the northern tip of Hamilton Island."},
        {"name": "Longitude 131 Uluru", "city": "Uluru", "price_per_night": 1650, "rating": 4.9, "amenities": ["Uluru view", "all inclusive", "luxury tents"], "description": "Luxury tented camp with direct views of Uluru."},
        {"name": "Crown Towers Melbourne", "city": "Melbourne", "price_per_night": 390, "rating": 4.7, "amenities": ["pool", "spa", "casino", "restaurants"], "description": "Southbank luxury tower with river and city views."},
        {"name": "YHA Sydney Harbour", "city": "Sydney", "price_per_night": 85, "rating": 4.5, "amenities": ["rooftop", "harbor view", "hostel option"], "description": "Budget hostel-hotel with rooftop views of the Harbour Bridge."},
    ],
    "egypt": [
        {"name": "Marriott Mena House Cairo", "city": "Cairo", "price_per_night": 340, "rating": 4.7, "amenities": ["pyramid view", "pool", "gardens"], "description": "Historic 1869 hotel with direct views of the Great Pyramid."},
        {"name": "Sofitel Legend Old Cataract Aswan", "city": "Aswan", "price_per_night": 420, "rating": 4.8, "amenities": ["Nile view", "pool", "spa"], "description": "Victorian-era palace hotel on the Nile, favorite of Agatha Christie."},
        {"name": "Winter Palace Luxor", "city": "Luxor", "price_per_night": 280, "rating": 4.6, "amenities": ["Nile view", "gardens", "pool"], "description": "Historic hotel from 1886 on the east bank of the Nile."},
        {"name": "Four Seasons Sharm El Sheikh", "city": "Sharm El Sheikh", "price_per_night": 380, "rating": 4.8, "amenities": ["private beach", "3 pools", "spa", "diving"], "description": "Beachfront resort on the Red Sea with house reef access."},
        {"name": "Steigenberger Nile Palace", "city": "Luxor", "price_per_night": 160, "rating": 4.5, "amenities": ["Nile view", "pool", "restaurant"], "description": "Mid-range Nile-side hotel across from Luxor Temple."},
    ],
    "greece": [
        {"name": "Canaves Oia Suites", "city": "Santorini", "price_per_night": 780, "rating": 4.9, "amenities": ["caldera view", "infinity pools", "spa"], "description": "Cliffside suites in Oia with private plunge pools and caldera views."},
        {"name": "Grande Bretagne Athens", "city": "Athens", "price_per_night": 490, "rating": 4.8, "amenities": ["Acropolis view", "rooftop pool", "spa"], "description": "Historic Syntagma Square hotel with a legendary rooftop bar."},
        {"name": "Blue Palace Crete", "city": "Crete", "price_per_night": 620, "rating": 4.9, "amenities": ["private beach", "spa", "villas", "sea view"], "description": "Cliffside resort in Elounda with views of Spinalonga island."},
        {"name": "Katikies Mykonos", "city": "Mykonos", "price_per_night": 890, "rating": 4.8, "amenities": ["private beach", "spa", "pool", "sea view"], "description": "Adults-only beachfront hotel on Agios Ioannis Beach."},
        {"name": "Fresh Hotel Athens", "city": "Athens", "price_per_night": 140, "rating": 4.4, "amenities": ["rooftop pool", "free wifi", "restaurant"], "description": "Design hotel near Monastiraki with an Acropolis-view rooftop."},
    ],
    "vietnam": [
        {"name": "Sofitel Legend Metropole Hanoi", "city": "Hanoi", "price_per_night": 380, "rating": 4.8, "amenities": ["pool", "spa", "colonial building"], "description": "1901 colonial hotel in Hanoi's French Quarter."},
        {"name": "Anantara Hoi An", "city": "Hoi An", "price_per_night": 260, "rating": 4.7, "amenities": ["river view", "pool", "spa", "bikes"], "description": "Riverside resort a short walk from Hoi An's ancient town."},
        {"name": "InterContinental Danang", "city": "Da Nang", "price_per_night": 480, "rating": 4.9, "amenities": ["private beach", "funicular", "spa", "pool"], "description": "Bill Bensley-designed peninsula resort with a private funicular to the beach."},
        {"name": "Six Senses Con Dao", "city": "Con Dao Islands", "price_per_night": 720, "rating": 4.9, "amenities": ["beachfront villas", "spa", "dive center"], "description": "Remote luxury on Con Son Island."},
        {"name": "The Reverie Saigon", "city": "Ho Chi Minh City", "price_per_night": 340, "rating": 4.7, "amenities": ["Italian design", "spa", "pool", "restaurant"], "description": "Opulent Italian-designed hotel in downtown Ho Chi Minh City."},
    ],
    "portugal": [
        {"name": "Belmond Reid's Palace", "city": "Madeira", "price_per_night": 620, "rating": 4.9, "amenities": ["cliffside pools", "spa", "afternoon tea"], "description": "Cliffside grand hotel above the Atlantic, on Madeira since 1891."},
        {"name": "Four Seasons Ritz Lisbon", "city": "Lisbon", "price_per_night": 490, "rating": 4.8, "amenities": ["rooftop running track", "spa", "Eduardo VII Park view"], "description": "Mid-century modern grand hotel overlooking Eduardo VII Park."},
        {"name": "The Yeatman", "city": "Porto", "price_per_night": 420, "rating": 4.9, "amenities": ["wine spa", "Michelin restaurant", "Douro view", "pool"], "description": "Wine-themed hotel overlooking the Douro and Porto's old town."},
        {"name": "Vila Vita Parc Algarve", "city": "Algarve", "price_per_night": 580, "rating": 4.8, "amenities": ["private beach", "6 restaurants", "spa", "pools"], "description": "Cliffside resort estate near Porches on the Algarve coast."},
        {"name": "Ibis Lisboa Jose Malhoa", "city": "Lisbon", "price_per_night": 85, "rating": 4.2, "amenities": ["free wifi", "24hr desk", "breakfast"], "description": "Budget option in central Lisbon near Praca de Espanha."},
    ],
}


FLIGHTS_DB = {
    ("SFO", "HND"): [
        {"flight_no": "UA837", "airline": "United", "price": 780, "depart": "10:30", "return": "18:00", "stops": 0, "notes": "Direct, wide-body 777."},
        {"flight_no": "NH107", "airline": "ANA", "price": 920, "depart": "11:45", "return": "16:30", "stops": 0, "notes": "Direct, premium service."},
        {"flight_no": "DL167", "airline": "Delta", "price": 690, "depart": "01:15", "return": "22:00", "stops": 1, "notes": "1 stop in SEA, red-eye departure."},
    ],
    ("LAX", "HND"): [
        {"flight_no": "NH105", "airline": "ANA", "price": 850, "depart": "11:45", "return": "16:30", "stops": 0, "notes": "Direct."},
        {"flight_no": "JL61", "airline": "JAL", "price": 890, "depart": "13:15", "return": "17:45", "stops": 0, "notes": "Direct."},
        {"flight_no": "AA167", "airline": "American", "price": 720, "depart": "23:30", "return": "07:00", "stops": 1, "notes": "1 stop in DFW."},
    ],
    ("SFO", "HYD"): [
        {"flight_no": "AI174", "airline": "Air India", "price": 1100, "depart": "21:15", "return": "01:00", "stops": 0, "notes": "Direct."},
        {"flight_no": "EK226", "airline": "Emirates", "price": 1250, "depart": "16:00", "return": "08:00", "stops": 1, "notes": "1 stop in DXB."},
        {"flight_no": "QR738", "airline": "Qatar", "price": 1180, "depart": "18:30", "return": "10:15", "stops": 1, "notes": "1 stop in DOH."},
    ],
    ("JFK", "BOM"): [
        {"flight_no": "EK234", "airline": "Emirates", "price": 980, "depart": "22:00", "return": "08:00", "stops": 1, "notes": "1 stop in DXB."},
        {"flight_no": "AI102", "airline": "Air India", "price": 1050, "depart": "19:30", "return": "05:45", "stops": 0, "notes": "Direct."},
        {"flight_no": "TK4", "airline": "Turkish", "price": 890, "depart": "23:15", "return": "10:00", "stops": 1, "notes": "1 stop in IST."},
    ],
    ("SFO", "CDG"): [
        {"flight_no": "AF83", "airline": "Air France", "price": 720, "depart": "16:30", "return": "11:00", "stops": 0, "notes": "Direct."},
        {"flight_no": "UA990", "airline": "United", "price": 680, "depart": "18:45", "return": "13:30", "stops": 0, "notes": "Direct."},
        {"flight_no": "LH457", "airline": "Lufthansa", "price": 640, "depart": "15:00", "return": "10:45", "stops": 1, "notes": "1 stop in FRA."},
    ],
    ("JFK", "CDG"): [
        {"flight_no": "DL264", "airline": "Delta", "price": 650, "depart": "21:45", "return": "13:30", "stops": 0, "notes": "Direct."},
        {"flight_no": "AF23", "airline": "Air France", "price": 690, "depart": "19:30", "return": "10:15", "stops": 0, "notes": "Direct."},
        {"flight_no": "B62", "airline": "La Compagnie", "price": 1450, "depart": "20:00", "return": "12:00", "stops": 0, "notes": "All-business direct."},
    ],
    ("LAX", "BKK"): [
        {"flight_no": "TG795", "airline": "Thai Airways", "price": 890, "depart": "23:30", "return": "06:00", "stops": 0, "notes": "Direct."},
        {"flight_no": "SQ12", "airline": "Singapore", "price": 1020, "depart": "22:15", "return": "10:30", "stops": 1, "notes": "1 stop in SIN."},
        {"flight_no": "KE18", "airline": "Korean Air", "price": 830, "depart": "22:00", "return": "05:15", "stops": 1, "notes": "1 stop in ICN."},
    ],
    ("JFK", "BKK"): [
        {"flight_no": "QR728", "airline": "Qatar", "price": 1050, "depart": "20:00", "return": "05:00", "stops": 1, "notes": "1 stop in DOH."},
        {"flight_no": "EK208", "airline": "Emirates", "price": 1120, "depart": "22:30", "return": "07:45", "stops": 1, "notes": "1 stop in DXB."},
    ],
    ("JFK", "FRA"): [
        {"flight_no": "LH401", "airline": "Lufthansa", "price": 690, "depart": "18:15", "return": "10:30", "stops": 0, "notes": "Direct."},
        {"flight_no": "UA960", "airline": "United", "price": 720, "depart": "17:00", "return": "13:15", "stops": 0, "notes": "Direct."},
    ],
    ("SFO", "HAM"): [
        {"flight_no": "LH491", "airline": "Lufthansa", "price": 840, "depart": "15:00", "return": "12:30", "stops": 1, "notes": "1 stop in FRA."},
        {"flight_no": "KL606", "airline": "KLM", "price": 810, "depart": "17:45", "return": "14:00", "stops": 1, "notes": "1 stop in AMS."},
    ],
    ("SFO", "FCO"): [
        {"flight_no": "AZ621", "airline": "ITA Airways", "price": 780, "depart": "17:00", "return": "12:45", "stops": 0, "notes": "Direct."},
        {"flight_no": "UA84", "airline": "United", "price": 810, "depart": "16:30", "return": "13:15", "stops": 0, "notes": "Direct."},
        {"flight_no": "LH459", "airline": "Lufthansa", "price": 740, "depart": "15:00", "return": "11:00", "stops": 1, "notes": "1 stop in FRA."},
    ],
    ("JFK", "FCO"): [
        {"flight_no": "AZ611", "airline": "ITA Airways", "price": 620, "depart": "22:15", "return": "10:00", "stops": 0, "notes": "Direct."},
        {"flight_no": "DL414", "airline": "Delta", "price": 660, "depart": "20:00", "return": "12:30", "stops": 0, "notes": "Direct."},
    ],
    ("SFO", "MAD"): [
        {"flight_no": "IB6172", "airline": "Iberia", "price": 730, "depart": "17:00", "return": "13:00", "stops": 0, "notes": "Direct."},
        {"flight_no": "LH459", "airline": "Lufthansa", "price": 690, "depart": "15:00", "return": "10:45", "stops": 1, "notes": "1 stop in FRA."},
    ],
    ("JFK", "LHR"): [
        {"flight_no": "BA112", "airline": "British Airways", "price": 580, "depart": "21:15", "return": "10:30", "stops": 0, "notes": "Direct."},
        {"flight_no": "AA100", "airline": "American", "price": 610, "depart": "18:45", "return": "09:15", "stops": 0, "notes": "Direct."},
        {"flight_no": "VS4", "airline": "Virgin Atlantic", "price": 640, "depart": "22:30", "return": "11:00", "stops": 0, "notes": "Direct."},
    ],
    ("SFO", "LHR"): [
        {"flight_no": "BA286", "airline": "British Airways", "price": 720, "depart": "18:30", "return": "14:00", "stops": 0, "notes": "Direct."},
        {"flight_no": "UA930", "airline": "United", "price": 690, "depart": "16:45", "return": "13:15", "stops": 0, "notes": "Direct."},
    ],
    ("LAX", "GRU"): [
        {"flight_no": "LA531", "airline": "LATAM", "price": 890, "depart": "22:30", "return": "13:00", "stops": 0, "notes": "Direct."},
        {"flight_no": "AA959", "airline": "American", "price": 920, "depart": "20:15", "return": "10:45", "stops": 1, "notes": "1 stop in MIA."},
    ],
    ("JFK", "GRU"): [
        {"flight_no": "LA8181", "airline": "LATAM", "price": 780, "depart": "22:00", "return": "11:30", "stops": 0, "notes": "Direct."},
        {"flight_no": "DL105", "airline": "Delta", "price": 820, "depart": "21:15", "return": "10:00", "stops": 0, "notes": "Direct."},
    ],
    ("LAX", "MEX"): [
        {"flight_no": "AM19", "airline": "Aeromexico", "price": 340, "depart": "07:30", "return": "16:45", "stops": 0, "notes": "Direct."},
        {"flight_no": "AA1120", "airline": "American", "price": 320, "depart": "09:00", "return": "18:15", "stops": 0, "notes": "Direct."},
    ],
    ("SFO", "MEX"): [
        {"flight_no": "AM657", "airline": "Aeromexico", "price": 380, "depart": "12:00", "return": "20:00", "stops": 0, "notes": "Direct."},
        {"flight_no": "UA1291", "airline": "United", "price": 410, "depart": "08:15", "return": "16:30", "stops": 0, "notes": "Direct."},
    ],
    ("LAX", "SYD"): [
        {"flight_no": "QF12", "airline": "Qantas", "price": 1180, "depart": "22:30", "return": "12:00", "stops": 0, "notes": "Direct, A380."},
        {"flight_no": "UA839", "airline": "United", "price": 1090, "depart": "22:00", "return": "10:30", "stops": 0, "notes": "Direct."},
        {"flight_no": "DL41", "airline": "Delta", "price": 1140, "depart": "22:45", "return": "11:15", "stops": 0, "notes": "Direct."},
    ],
    ("SFO", "SYD"): [
        {"flight_no": "QF74", "airline": "Qantas", "price": 1240, "depart": "22:00", "return": "10:00", "stops": 0, "notes": "Direct."},
        {"flight_no": "UA863", "airline": "United", "price": 1180, "depart": "21:15", "return": "09:30", "stops": 0, "notes": "Direct."},
    ],
    ("JFK", "CAI"): [
        {"flight_no": "MS986", "airline": "EgyptAir", "price": 780, "depart": "22:30", "return": "11:00", "stops": 0, "notes": "Direct."},
        {"flight_no": "TK4", "airline": "Turkish", "price": 720, "depart": "23:15", "return": "10:30", "stops": 1, "notes": "1 stop in IST."},
    ],
    ("JFK", "ATH"): [
        {"flight_no": "A311", "airline": "Aegean", "price": 680, "depart": "21:45", "return": "12:00", "stops": 0, "notes": "Direct, seasonal."},
        {"flight_no": "DL126", "airline": "Delta", "price": 720, "depart": "20:00", "return": "10:45", "stops": 0, "notes": "Direct."},
        {"flight_no": "LH405", "airline": "Lufthansa", "price": 640, "depart": "17:30", "return": "09:15", "stops": 1, "notes": "1 stop in FRA."},
    ],
    ("SFO", "SGN"): [
        {"flight_no": "EK226", "airline": "Emirates", "price": 1080, "depart": "16:00", "return": "07:30", "stops": 1, "notes": "1 stop in DXB."},
        {"flight_no": "SQ2", "airline": "Singapore", "price": 1150, "depart": "23:45", "return": "11:00", "stops": 1, "notes": "1 stop in SIN."},
    ],
    ("JFK", "LIS"): [
        {"flight_no": "TP208", "airline": "TAP Portugal", "price": 580, "depart": "22:00", "return": "10:30", "stops": 0, "notes": "Direct."},
        {"flight_no": "DL144", "airline": "Delta", "price": 620, "depart": "21:30", "return": "11:00", "stops": 0, "notes": "Direct."},
    ],
    ("SFO", "LIS"): [
        {"flight_no": "TP258", "airline": "TAP Portugal", "price": 720, "depart": "17:00", "return": "13:30", "stops": 0, "notes": "Direct, seasonal."},
        {"flight_no": "LH459", "airline": "Lufthansa", "price": 680, "depart": "15:00", "return": "10:45", "stops": 1, "notes": "1 stop in FRA."},
    ],
}

VISA_RULES_DB = {
    "japan": "Tourist visa-free for 90 days for US citizens. Passport must be valid 6 months beyond entry. No visa fee.",
    "india": "e-Visa required. Apply online at least 4 days before travel. $25 fee. 30-day tourist validity. Passport valid 6 months.",
    "france": "Schengen visa-free for 90 days within any 180-day period for US citizens. Passport valid 3 months beyond departure.",
    "thailand": "Visa on arrival for 30 days for US citizens. $35 fee, payable in Thai baht. Proof of onward travel required. Passport valid 6 months.",
    "germany": "Schengen visa-free for 90 days within any 180-day period for US citizens. Passport valid 3 months beyond departure.",
    "italy": "Schengen visa-free for 90 days within any 180-day period for US citizens. Passport valid 3 months beyond departure.",
    "spain": "Schengen visa-free for 90 days within any 180-day period for US citizens. Passport valid 3 months beyond departure.",
    "uk": "Tourist visa-free for 6 months for US citizens. ETA required from 2025 - apply online, $12 fee. Passport valid for duration of stay.",
    "brazil": "Tourist visa-free for 90 days for US citizens as of 2025. Extendable once. Passport valid 6 months.",
    "mexico": "Tourist card (FMM) for 180 days, issued on arrival, no fee for stays under 7 days. Passport valid for duration of stay.",
    "australia": "eVisitor or ETA required for US citizens. Apply online, $20 fee. 3-month stays, multiple entry within 12 months.",
    "egypt": "Visa on arrival for 30 days for US citizens. $25 fee, USD only. e-Visa also available online. Passport valid 6 months.",
    "greece": "Schengen visa-free for 90 days within any 180-day period for US citizens. Passport valid 3 months beyond departure.",
    "vietnam": "e-Visa required. Apply online, $25 fee, 30-day single-entry validity. Passport valid 6 months.",
    "portugal": "Schengen visa-free for 90 days within any 180-day period for US citizens. Passport valid 3 months beyond departure.",
}


ITINERARY_TEMPLATES = {
    "japan": "Day 1: Tokyo arrival, Shibuya Crossing, dinner in Shinjuku. Day 2: Senso-ji Temple in Asakusa, teamLab digital art. Day 3: Bullet train to Kyoto, Fushimi Inari at dusk. Day 4: Arashiyama bamboo grove, Kinkaku-ji. Day 5: Nara day trip, deer park. Day 6: Osaka, Dotonbori street food. Day 7: Departure.",
    "india": "Day 1: Delhi arrival, Red Fort and Jama Masjid. Day 2: Qutub Minar, Humayun's Tomb. Day 3: Drive to Agra, Taj Mahal at sunset. Day 4: Fatehpur Sikri, drive to Jaipur. Day 5: Amber Fort, Hawa Mahal. Day 6: Fly to Udaipur, Lake Pichola boat ride. Day 7: Departure via Delhi.",
    "france": "Day 1: Paris arrival, Eiffel Tower at sunset. Day 2: Louvre, Seine river cruise. Day 3: Versailles day trip. Day 4: Montmartre, Sacre-Coeur. Day 5: TGV to Nice, promenade des Anglais. Day 6: Eze village, Monaco day trip. Day 7: Departure.",
    "thailand": "Day 1: Bangkok arrival, Grand Palace. Day 2: Wat Arun, floating market, Chinatown. Day 3: Fly to Chiang Mai, Doi Suthep. Day 4: Elephant sanctuary, night bazaar. Day 5: Fly to Phuket, beach day. Day 6: Phi Phi islands boat trip. Day 7: Departure.",
    "germany": "Day 1: Berlin arrival, Brandenburg Gate, Reichstag. Day 2: Museum Island, Berlin Wall Memorial. Day 3: Train to Munich, Marienplatz. Day 4: Neuschwanstein Castle day trip. Day 5: Train to Cologne, Cathedral. Day 6: Rhine Valley wine towns. Day 7: Departure.",
    "italy": "Day 1: Rome arrival, Colosseum and Roman Forum. Day 2: Vatican Museums, Sistine Chapel, Trevi Fountain. Day 3: Train to Florence, Duomo, Uffizi. Day 4: Tuscany day trip. Day 5: Train to Venice, St. Mark's Square. Day 6: Murano and Burano islands. Day 7: Departure.",
    "spain": "Day 1: Barcelona arrival, Sagrada Familia, Gothic Quarter. Day 2: Park Guell, Casa Batllo, Barceloneta beach. Day 3: Fly to Seville, Cathedral and Alcazar. Day 4: Cordoba day trip, Mezquita. Day 5: Train to Granada, Alhambra. Day 6: Fly to Madrid, Prado Museum. Day 7: Departure.",
    "uk": "Day 1: London arrival, Tower of London, Tower Bridge. Day 2: Westminster Abbey, Parliament, British Museum. Day 3: Windsor Castle day trip. Day 4: Train to Edinburgh, Royal Mile. Day 5: Edinburgh Castle, Arthur's Seat hike. Day 6: Highlands day tour, Loch Ness. Day 7: Departure.",
    "brazil": "Day 1: Rio arrival, Copacabana Beach. Day 2: Christ the Redeemer, Sugarloaf Mountain. Day 3: Ipanema, Santa Teresa neighborhood. Day 4: Fly to Iguazu, Brazilian side of falls. Day 5: Argentine side of falls. Day 6: Fly to Salvador, Pelourinho. Day 7: Departure.",
    "mexico": "Day 1: Mexico City arrival, Zocalo, Templo Mayor. Day 2: Teotihuacan pyramids day trip. Day 3: Frida Kahlo Museum, Coyoacan. Day 4: Fly to Merida, Yucatan. Day 5: Chichen Itza and cenote. Day 6: Tulum ruins and beach. Day 7: Departure.",
    "australia": "Day 1: Sydney arrival, Opera House, Circular Quay. Day 2: Bondi to Coogee coastal walk, Harbor Bridge climb. Day 3: Blue Mountains day trip. Day 4: Fly to Cairns, Great Barrier Reef snorkeling. Day 5: Daintree Rainforest tour. Day 6: Fly to Uluru, sunset viewing. Day 7: Departure.",
    "egypt": "Day 1: Cairo arrival, Pyramids of Giza and Sphinx. Day 2: Egyptian Museum, Khan el-Khalili bazaar. Day 3: Fly to Luxor, Karnak Temple. Day 4: Valley of the Kings, Hatshepsut Temple. Day 5: Nile cruise begins, Edfu Temple. Day 6: Aswan, Philae Temple. Day 7: Departure.",
    "greece": "Day 1: Athens arrival, Acropolis and Parthenon. Day 2: Ancient Agora, Plaka neighborhood. Day 3: Delphi day trip. Day 4: Ferry to Santorini, Oia sunset. Day 5: Santorini caldera boat tour. Day 6: Ferry to Mykonos, beaches. Day 7: Departure.",
    "vietnam": "Day 1: Hanoi arrival, Old Quarter walking tour. Day 2: Ho Chi Minh Mausoleum, Temple of Literature. Day 3: Halong Bay overnight cruise. Day 4: Return to Hanoi, fly to Hoi An. Day 5: Hoi An Ancient Town, lantern night. Day 6: Fly to Ho Chi Minh City, Cu Chi Tunnels. Day 7: Departure.",
    "portugal": "Day 1: Lisbon arrival, Alfama district, Fado dinner. Day 2: Belem Tower, Jeronimos Monastery. Day 3: Sintra day trip, Pena Palace. Day 4: Train to Porto, Ribeira district. Day 5: Douro Valley wine tour. Day 6: Porto old town, Livraria Lello. Day 7: Departure.",
}

EMAIL_LOG = []
PAYMENT_LOG = []